# Generated by Django 3.1 on 2020-08-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ProductColor',
            new_name='productcolor',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='color',
            table='colors',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productcolor',
            table='product_colors',
        ),
        migrations.AlterModelTable(
            name='productsize',
            table='product_sizes',
        ),
        migrations.AlterModelTable(
            name='productsizechart',
            table='product_size_charts',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
        migrations.AlterModelTable(
            name='sizechart',
            table='size_charts',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
