# Generated by Django 3.1 on 2020-08-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200820_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsizechart',
            old_name='SizeChart',
            new_name='sizechart',
        ),
        migrations.RenameField(
            model_name='sizechart',
            old_name='length',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='image',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='width',
        ),
    ]
