# Generated by Django 3.1 on 2020-08-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdtime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedtime',
            new_name='updated_time',
        ),
    ]
